import {parseOtpAuth,totp} from './crypto.js';import {exists,createVault,unlock,saveAccount,deleteAccount,exportVault,importVault} from './storage.js';
const $=s=>document.querySelector(s);let accounts=[],passphrase=null,ticker=null,idle=null,stream=null,scanning=false;const toast=t=>{$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)};
async function gate(){const has=await exists();$('#gateTitle').textContent=has?'Unlock vault':'Create your vault';$('#gateText').textContent=has?'Enter your passphrase. Decryption happens only in memory.':'Your tokens stay encrypted on this device. Nothing leaves the browser.';$('#importStart').hidden=has;}
function resetIdle(){clearTimeout(idle);if(passphrase)idle=setTimeout(lock,5*60*1000)};['pointerdown','keydown'].forEach(e=>addEventListener(e,resetIdle));
function lock(){passphrase=null;accounts=[];$('#cards').replaceChildren();clearInterval(ticker);ticker=null;$('#app').hidden=true;$('#gate').hidden=false;$('#lock').hidden=true;$('#pass').value='';$('#gateTitle').textContent='Unlock vault';$('#gateText').textContent='Vault locked. Plaintext keys were dropped from app memory.';stopCamera();}
async function render(){const now=Date.now();$('#cards').innerHTML='';for(const a of accounts){const rem=a.period-Math.floor(now/1000)%a.period,code=await totp(a.secret,a.algorithm,a.digits,a.period,now);const el=document.createElement('article');el.className='card';el.innerHTML=`<button class="delete" aria-label="Delete">×</button><div class="issuer"></div><div class="account"></div><div class="code" title="Copy code"></div><div class="meta"><span>${a.algorithm} · ${a.digits} DIGITS · ${a.period}S</span><span class="ring">${rem}s</span></div>`;el.querySelector('.issuer').textContent=a.issuer||'Authenticator';el.querySelector('.account').textContent=a.account;el.querySelector('.code').textContent=code.replace(/(.{3,4})(?=.)/g,'$1 ');el.querySelector('.code').onclick=()=>copy(code);el.querySelector('.delete').onclick=async()=>{if(confirm(`Delete ${a.account}?`)){await deleteAccount(a.id);accounts=accounts.filter(x=>x.id!==a.id);render()}};$('#cards').append(el)}if(!accounts.length)$('#cards').innerHTML='<div class="card"><div class="issuer">No tokens yet</div><div class="account">Add an otpauth URI or scan a QR code.</div></div>'}
async function copy(code){await navigator.clipboard.writeText(code);toast('Copied · clears in 30s');setTimeout(async()=>{try{if(await navigator.clipboard.readText()===code)await navigator.clipboard.writeText('')}catch{}},30000)}
async function addRaw(raw){const a=parseOtpAuth(raw.trim());await saveAccount(a,passphrase);accounts.push(a);await render();toast('Encrypted & saved')}
$('#gateForm').onsubmit=async e=>{e.preventDefault();$('#gateError').textContent='';const p=$('#pass').value;try{if(!await exists())await createVault(p);accounts=await unlock(p);passphrase=p;$('#gate').hidden=true;$('#app').hidden=false;$('#lock').hidden=false;await render();ticker=setInterval(render,1000);resetIdle()}catch(x){$('#gateError').textContent=x.message}};
$('#lock').onclick=lock;$('#add').onclick=()=>{$('#addDialog').showModal();$('#uri').focus()};$('#save').onclick=async()=>{try{await addRaw($('#uri').value);$('#uri').value='';$('#addDialog').close();$('#addError').textContent=''}catch(x){$('#addError').textContent=x.message}};
$('#export').onclick=async()=>{const data=await exportVault(passphrase),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`keyring-auth-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importStart').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{const obj=JSON.parse(await e.target.files[0].text()),p=prompt('Passphrase for this encrypted backup');if(!p)return;await importVault(obj,p);location.reload()}catch(x){$('#gateError').textContent=x.message}};
async function startCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});$('#video').srcObject=stream;scanning=true;requestAnimationFrame(scanFrame)}catch(x){$('#scanStatus').textContent='Camera unavailable. Paste the otpauth URI instead.'}}
function stopCamera(){scanning=false;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null}async function scanFrame(){if(!scanning)return;const v=$('#video'),c=$('#canvas');if(v.readyState>=2){c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(v,0,0);const im=x.getImageData(0,0,c.width,c.height),qr=jsQR(im.data,c.width,c.height,{inversionAttempts:'dontInvert'});if(qr?.data?.startsWith('otpauth://')){try{await addRaw(qr.data);stopCamera();$('#scanDialog').close();return}catch(e){$('#scanStatus').textContent=e.message}}}requestAnimationFrame(scanFrame)}
$('#scan').onclick=()=>{$('#scanDialog').showModal();startCamera()};$('#closeScan').onclick=stopCamera;$('#scanDialog').addEventListener('close',stopCamera);gate();
