import {parseOtpAuth,totp} from './crypto.js?v=3';import {exists,createVault,unlock,saveAccount,deleteAccount,exportVault,rotateVault,importVault} from './storage.js?v=5';
const $=s=>document.querySelector(s);let accounts=[],vaultKey=null,ticker=null,idle=null,stream=null,scanning=false;
const message=e=>e instanceof Error?e.message:'Something went wrong. Nothing was changed.';
const toast=t=>{$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2200);};
async function gate(){const has=await exists();$('#gateTitle').textContent=has?'Unlock vault':'Create your vault';$('#gateText').textContent=has?'Enter your passphrase. Decryption happens only in memory.':'Your tokens stay encrypted on this device. Nothing leaves the browser.';$('#importStart').hidden=has;}
function resetIdle(){clearTimeout(idle);if(vaultKey)idle=setTimeout(lock,5*60*1000);}['pointerdown','keydown'].forEach(e=>addEventListener(e,resetIdle,{passive:true}));
function lock(){vaultKey=null;accounts=[];$('#cards').replaceChildren();clearInterval(ticker);ticker=null;$('#app').hidden=true;$('#gate').hidden=false;$('#lock').hidden=true;$('#security').hidden=true;$('#pass').value='';$('#gateTitle').textContent='Unlock vault';$('#gateText').textContent='Vault locked. The session key and plaintext tokens were dropped from memory.';stopCamera();}
async function render(){const now=Date.now();if(!accounts.length){$('#cards').innerHTML='<div class="empty"><div class="emptyMark">＋</div><h3>No tokens yet</h3><p>Add an authenticator link or scan a QR code.</p></div>';return;}const rows=await Promise.all(accounts.map(async a=>{const rem=a.period-Math.floor(now/1000)%a.period,code=await totp(a.secret,a.algorithm,a.digits,a.period,now);return {a,rem,code};}));const existing=new Map([...$('#cards').children].map(el=>[el.dataset.id,el]));for(const {a,rem,code} of rows){let el=existing.get(a.id);if(!el){el=document.createElement('article');el.className='card';el.dataset.id=a.id;el.innerHTML='<div class="cardTop"><div><div class="issuer"></div><div class="account"></div></div><button class="delete" aria-label="Delete account">×</button></div><button class="code" title="Copy code"></button><div class="progress" aria-hidden="true"><i></i></div><div class="meta"><span class="spec"></span><span class="time"></span></div>';el.querySelector('.issuer').textContent=a.issuer||'Authenticator';el.querySelector('.account').textContent=a.account;el.querySelector('.spec').textContent=`${a.algorithm} · ${a.digits} digits`;el.querySelector('.delete').onclick=async()=>{if(confirm(`Delete ${a.account}? This cannot be undone.`)){try{await deleteAccount(a.id);accounts=accounts.filter(x=>x.id!==a.id);el.remove();await render();toast('Account deleted');}catch(e){toast(message(e));}}};$('#cards').append(el);}el.querySelector('.code').textContent=code.replace(/(.{3,4})(?=.)/g,'$1 ');el.querySelector('.code').onclick=()=>copy(code);el.querySelector('.time').textContent=`${rem}s`;el.querySelector('.progress i').style.transform=`scaleX(${rem/a.period})`;existing.delete(a.id);}for(const stale of existing.values())stale.remove();}
async function copy(code){try{await navigator.clipboard.writeText(code);toast('Code copied · clipboard clears in 30s');setTimeout(async()=>{try{if(await navigator.clipboard.readText()===code)await navigator.clipboard.writeText('');}catch{}},30000);}catch{toast('Press and hold the code to copy it.');}}
async function addRaw(raw){const a=parseOtpAuth(raw.trim());await saveAccount(a,vaultKey);accounts.push(a);await render();toast('Encrypted and saved');}
$('#gateForm').onsubmit=async e=>{e.preventDefault();$('#gateError').textContent='';const p=$('#pass').value;const submit=e.submitter;submit.disabled=true;submit.textContent='Opening…';try{if(!await exists())await createVault(p);const session=await unlock(p);vaultKey=session.key;accounts=session.accounts;$('#pass').value='';$('#gate').hidden=true;$('#app').hidden=false;$('#lock').hidden=false;$('#security').hidden=false;await render();ticker=setInterval(render,1000);resetIdle();}catch(x){$('#gateError').textContent=message(x);}finally{submit.disabled=false;submit.textContent='Continue';}};
$('#lock').onclick=lock;$('#add').onclick=()=>{$('#addDialog').showModal();$('#uri').focus();};$('#save').onclick=async()=>{try{await addRaw($('#uri').value);$('#uri').value='';$('#addDialog').close();$('#addError').textContent='';}catch(x){$('#addError').textContent=message(x);}};
$('#security').onclick=()=>{$('#securityError').textContent='';$('#securityDialog').showModal();$('#newPass').focus();};$('#rotate').onclick=async()=>{const next=$('#newPass').value,confirm=$('#confirmPass').value;if(next!==confirm){$('#securityError').textContent='The two passphrases do not match.';return;}const b=$('#rotate');b.disabled=true;b.textContent='Re-encrypting…';try{vaultKey=await rotateVault(vaultKey,next);$('#newPass').value=$('#confirmPass').value='';$('#securityDialog').close();resetIdle();toast('Vault re-encrypted with the new passphrase');}catch(e){$('#securityError').textContent=message(e);}finally{b.disabled=false;b.textContent='Re-encrypt vault';}};
$('#export').onclick=async()=>{try{const data=await exportVault(vaultKey),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`keyring-auth-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch(e){toast(message(e));}};
$('#importStart').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{const file=e.target.files?.[0];if(!file)return;const obj=JSON.parse(await file.text()),p=prompt('Enter the passphrase for this encrypted backup');if(!p)return;await importVault(obj,p);location.reload();}catch(x){$('#gateError').textContent=message(x);}finally{e.target.value='';}};
async function startCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});$('#video').srcObject=stream;scanning=true;requestAnimationFrame(scanFrame);}catch{$('#scanStatus').textContent='Camera access is unavailable. You can paste the authenticator link instead.';}}
function stopCamera(){scanning=false;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;}async function scanFrame(){if(!scanning)return;const v=$('#video'),c=$('#canvas');if(v.readyState>=2){c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(v,0,0);const im=x.getImageData(0,0,c.width,c.height),qr=jsQR(im.data,c.width,c.height,{inversionAttempts:'dontInvert'});if(qr?.data?.startsWith('otpauth://')){try{await addRaw(qr.data);stopCamera();$('#scanDialog').close();return;}catch(e){$('#scanStatus').textContent=message(e);}}}requestAnimationFrame(scanFrame);}
$('#scan').onclick=()=>{$('#scanDialog').showModal();startCamera();};$('#closeScan').onclick=stopCamera;$('#scanDialog').addEventListener('close',stopCamera);document.addEventListener('visibilitychange',()=>{if(document.hidden&&vaultKey)lock();});gate();
