import {enc} from './crypto.js?v=3';
const DB='keyring-auth',STORE='vault',META='meta',ITERATIONS=650000;
const open=()=>new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(new Error('This browser could not open the vault.'));});
async function get(k){const d=await open();return new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(new Error('The vault could not be read.'));});}
async function put(k,v){const d=await open();return new Promise((ok,no)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(v,k);r.onsuccess=()=>ok();r.onerror=()=>no(new Error('The vault could not be saved.'));});}
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))),unb=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(pass,salt){const material=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:ITERATIONS},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function seal(data,key){const iv=crypto.getRandomValues(new Uint8Array(12)),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(data)));return {iv:b64(iv),ciphertext:b64(ct)};}
async function unseal(rec,key){try{const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb(rec.iv)},key,unb(rec.ciphertext));return JSON.parse(new TextDecoder().decode(pt));}catch{throw new Error('That passphrase did not unlock this vault.');}}
async function records(){const out=[];const d=await open();await new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).openCursor();r.onsuccess=()=>{const c=r.result;if(!c)return ok();if(c.key!==META)out.push([c.key,c.value]);c.continue();};r.onerror=()=>no(new Error('The vault could not be read.'));});return out;}
async function replaceAll(meta,items){const d=await open();return new Promise((ok,no)=>{const tx=d.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);s.clear();s.put(meta,META);for(const [id,rec] of items)s.put(rec,id);tx.oncomplete=()=>ok();tx.onerror=()=>no(new Error('Nothing changed. The vault could not be re-encrypted.'));});}
export async function exists(){return !!(await get(META));}
export async function createVault(pass){if(pass.length<10)throw new Error('Use at least 10 characters.');const salt=crypto.getRandomValues(new Uint8Array(16)),key=await derive(pass,salt),meta={version:2,kdf:'PBKDF2-SHA256',iterations:ITERATIONS,salt:b64(salt),check:await seal({ok:true},key)};await put(META,meta);return key;}
export async function unlock(pass){const m=await get(META);if(!m)throw new Error('No vault was found on this device.');const key=await derive(pass,unb(m.salt));await unseal(m.check,key);const encrypted=await records(),accounts=await Promise.all(encrypted.map(([,rec])=>unseal(rec,key)));return {key,accounts};}
export async function saveAccount(a,key){await put(a.id,await seal(a,key));}
export async function deleteAccount(id){const d=await open();return new Promise((ok,no)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=()=>ok();r.onerror=()=>no(new Error('That account could not be deleted.'));});}
export async function exportVault(key){const m=await get(META);await unseal(m.check,key);const data=Object.fromEntries(await records());return {format:'keyring-auth-backup',version:1,exportedAt:new Date().toISOString(),records:{meta:m,...data}};}
export async function rotateVault(key,newPass){if(newPass.length<10)throw new Error('Use at least 10 characters.');const old=await records(),plain=await Promise.all(old.map(async([id,rec])=>[id,await unseal(rec,key)])),salt=crypto.getRandomValues(new Uint8Array(16)),newKey=await derive(newPass,salt),meta={version:2,kdf:'PBKDF2-SHA256',iterations:ITERATIONS,salt:b64(salt),check:await seal({ok:true},newKey)},sealed=await Promise.all(plain.map(async([id,a])=>[id,await seal(a,newKey)]));await replaceAll(meta,sealed);return newKey;}
export async function importVault(obj,pass){if(obj?.format!=='keyring-auth-backup'||!obj.records?.meta)throw new Error('This is not a Keyring Auth backup.');const m=obj.records.meta,key=await derive(pass,unb(m.salt));await unseal(m.check,key);const items=Object.entries(obj.records).filter(([k])=>k!==META);await replaceAll(m,items);}
export {ITERATIONS};
