import {enc} from './crypto.js';
const DB='keyring-auth', STORE='vault', META='meta', ITERATIONS=650000;
const open=()=>new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
async function get(k){const d=await open();return new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});}
async function put(k,v){const d=await open();return new Promise((ok,no)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(v,k);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)});}
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))), unb=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(pass,salt){const m=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:ITERATIONS},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function seal(data,pass,salt){const iv=crypto.getRandomValues(new Uint8Array(12)), key=await derive(pass,salt), ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(data)));return {iv:b64(iv),ciphertext:b64(ct)};}
async function unseal(rec,pass,salt){try{const key=await derive(pass,salt),pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb(rec.iv)},key,unb(rec.ciphertext));return JSON.parse(new TextDecoder().decode(pt));}catch{throw new Error('Wrong passphrase or damaged vault');}}
export async function exists(){return !!(await get(META));}
export async function createVault(pass){if(pass.length<10)throw new Error('Use at least 10 characters');const salt=crypto.getRandomValues(new Uint8Array(16));await put(META,{version:1,kdf:'PBKDF2-SHA256',iterations:ITERATIONS,salt:b64(salt),check:await seal({ok:true},pass,salt)});}
export async function unlock(pass){const m=await get(META);if(!m)throw new Error('No vault');await unseal(m.check,pass,unb(m.salt));const encrypted=[];const d=await open();await new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).openCursor();r.onsuccess=()=>{const c=r.result;if(!c)return ok();if(c.key!==META)encrypted.push(c.value);c.continue()};r.onerror=()=>no(r.error)});return Promise.all(encrypted.map(rec=>unseal(rec,pass,unb(m.salt)));}
export async function saveAccount(a,pass){const m=await get(META);await put(a.id,await seal(a,pass,unb(m.salt)));}
export async function deleteAccount(id){const d=await open();return new Promise((ok,no)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)});}
export async function exportVault(pass){await unlock(pass);const m=await get(META),d=await open(),records={};await new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).openCursor();r.onsuccess=()=>{const c=r.result;if(!c)return ok();records[c.key]=c.value;c.continue()};r.onerror=()=>no(r.error)});return {format:'keyring-auth-backup',version:1,exportedAt:new Date().toISOString(),records};}
export async function importVault(obj,pass){if(obj?.format!=='keyring-auth-backup'||!obj.records?.meta)throw new Error('Invalid backup');const m=obj.records.meta;await unseal(m.check,pass,unb(m.salt));const d=await open();await new Promise((ok,no)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();for(const [k,v] of Object.entries(obj.records))tx.objectStore(STORE).put(v,k);tx.oncomplete=ok;tx.onerror=()=>no(tx.error)});}
export {ITERATIONS};
